SELECT *
  FROM A_ITEM;
 
SELECT *
  FROM A_OUT_M;

SELECT *
  FROM A_OUT_D;

--<요청연습>
--1)
select BRAND_CD, COUNT(INVOICE_NO) AS INVOICE
  from A_OUT_M
  group by BRAND_CD
  order by BRAND_CD desc;
 
--2)
select SUM(ORDER_QTY)
  from A_OUT_D
  where BRAND_CD = '1001'
    and ITEM_CD = 'A';
 
--3)
select BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
  from A_OUT_D
  where (BRAND_CD, INVOICE_NO) IN (
                                   select BRAND_CD, INVOICE_NO
                                     from A_OUT_M
                                    where OUTBOUND_DATE = '2023-01-03'
                                    )
  group by BRAND_CD, ITEM_CD
  order by BRAND_CD, ITEM_CD;
  
--3) 조인버전
select M2.BRAND_CD, M2.ITEM_CD, SUM(M2.ORDER_QTY)
  from A_OUT_M M1
       join A_OUT_D M2 ON M2.BRAND_CD = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
 where M1.OUTBOUND_DATE = '2023-01-03'
 GROUP BY M2.BRAND_CD, M2.ITEM_CD
 ORDER BY M2.BRAND_CD, M2.ITEM_CD;

--<조건조회>
--1)
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = '2023-01-03 ';
 
--2)
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = '2023-01-04'
   AND ORDER_NM = '김민기';
   
--3)
SELECT *
  FROM A_OUT_D
 WHERE ITEM_CD = 'A';
 
--4)
SELECT *
  FROM A_OUT_D D1
 WHERE D1.ITEM_CD = 'C'
   AND D1.ORDER_QTY > 2;

--5)
SELECT *
  FROM A_ITEM
 WHERE BRAND_CD = '1001';
 
--6)
SELECT OUTBOUND_DATE, BRAND_CD , INVOICE_NO , ORDER_NM  
  FROM A_OUT_M M1
 WHERE OUTBOUND_DATE = '2023-01-03'
    OR OUTBOUND_DATE = '2023-01-04';
-- IN 조건 활용
SELECT OUTBOUND_DATE, BRAND_CD , INVOICE_NO , ORDER_NM  
  FROM A_OUT_M M1
  WHERE OUTBOUND_DATE IN ('2023-01-03', '2023-01-04');

--7)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
   AND ITEM_CD IN ('A', 'B', 'C')
   AND ORDER_QTY > 3;
 
--8)
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE,ORDER_NM
  FROM A_OUT_M
  WHERE OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
    AND ORDER_NM IN ('윤현수', '김민기');
  
--9)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND ITEM_CD IN ('A', 'B', 'C')
   AND ORDER_QTY >= 3;
   
--10)
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
  FROM A_OUT_M
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND ORDER_NM LIKE '전%'
    OR ORDER_NM LIKE '권%';

--10-(1))
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
  FROM A_OUT_M
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND SUBSTR(ORDER_NM,2,3) IN ('전', '권');

--11)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY >=3 ;

--12)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY >=3
 ORDER BY ORDER_QTY DESC;
 
--13)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY >=3
 ORDER BY ORDER_QTY DESC, BRAND_CD, ITEM_CD DESC;
 
--14)

--15)
SELECT COUNT(INVOICE_NO)
  FROM A_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2023-01-03' AND '2023-01-04';
 
--16)
SELECT COUNT(ORDER_QTY)
  FROM A_OUT_D
 WHERE BRAND_CD = '1001';
 
--17)
SELECT BRAND_CD, COUNT(*) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
 ORDER BY INV_CNT DESC;
 
--18)
SELECT BRAND_CD, OUTBOUND_DATE, COUNT(*)
  FROM A_OUT_M
 GROUP BY BRAND_CD, OUTBOUND_DATE
 ORDER BY BRAND_CD, COUNT(*) DESC;
 
--19)
SELECT BRAND_CD, SUM(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD
 ORDER BY SUM(ORDER_QTY) DESC;
 
--20)
SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD, ITEM_CD 
 ORDER BY BRAND_CD , SUM(ORDER_QTY) DESC;

--21)
SELECT BRAND_CD, MIN(ORDER_QTY) AS 최소 , MAX(ORDER_QTY) AS 최대
  FROM A_OUT_D
 GROUP BY BRAND_CD;
 
--22)DAY5. SELECT 기본문형 익히기2 -> 실제 사례
SELECT INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-02'
   AND OUT_TYPE_DIV IN ('M15', 'M22')
   AND OUT_BOX_DIV LIKE 'F%'
   AND ORDER_PLACE = '52685'
 ORDER BY OUTBOUND_DATE, INVOICE_NO;
   
--22-(2))
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY-MM'), COUNT(1)
  FROM LO_OUT_M
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM');
 
--23)
SELECT OUTBOUND_DATE
       , COUNT(*)                    AS TOT_CNT
       , COUNT(DISTINCT OUT_BOX_DIV) AS OUT_BOX_CNT
       , MIN  (OUT_BOX_DIV)          AS OUT_BOX_MIN
       , MAX  (OUT_BOX_DIV)          AS OUT_BOX_MAX 
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2019/09/01' AND '2019/09/02'
   AND OUT_TYPE_DIV IN ('M15', 'M22')
   AND OUT_BOX_DIV LIKE 'F%'
   AND ORDER_PLACE = '52685'
 GROUP BY OUTBOUND_DATE
 ORDER BY OUTBOUND_DATE;
 
--24)
SELECT BRAND_CD, INVOICE_NO
  FROM A_OUT_D
 WHERE (BRAND_CD, INVOICE_NO)  IN (
                                    SELECT BRAND_CD, INVOICE_NO
                                      FROM A_OUT_M
                                     WHERE OUTBOUND_DATE = '2023-01-03'
                                      );

--25)
SELECT BRAND_CD, INVOICE_NO
  FROM A_OUT_D
 WHERE (BRAND_CD, INVOICE_NO) IN (
                                   SELECT BRAND_CD,INVOICE_NO
                                     FROM A_OUT_M
                                    WHERE BRAND_CD = '1001'
                                      AND OUT_TYPE_DIV LIKE 'M1%'
                                    );
                         
--26)
SELECT *  
  FROM A_OUT_M
 WHERE (INVOICE_NO, BRAND_CD) IN (
                                      SELECT INVOICE_NO, BRAND_CD
                                        FROM A_OUT_D
                                       GROUP BY INVOICE_NO, BRAND_CD
                                      HAVING SUM(ORDER_QTY) >= 3
                                      );
                                      
--27)
SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
       , (SELECT *
            FROM A_ITEM S1
           WHERE S1.BRAND_CD = M1.BRAND_CD
             AND S1.ITEM_CD = M1.ITEM_CD
         ) AS ITEM_NM
  FROM A_OUT_D M1
 GROUP BY BRAND_CD, ITEM_CD
 ORDER BY BRAND_CD, SUM(ORDER_QTY) DESC;
 
--27-(1))
SELECT M1.BRAND_CD, M1.ITEM_CD, S1.ITEM_NM, SUM(M1.ORDER_QTY)
  FROM A_OUT_D M1
       JOIN A_ITEM S1 ON S1.BRAND_CD = M1.BRAND_CD
                     AND S1.ITEM_CD  = M1.ITEM_CD
 GROUP BY M1.BRAND_CD, M1.ITEM_CD, S1.ITEM_NM
 ORDER BY M1.BRAND_CD, SUM(M1.ORDER_QTY) DESC;

--28)
SELECT OUTBOUND_DATE
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE >= :OUTBOUND_DATE;

--28-(1))
SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 1 AS FROM_DATE
       ,TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 10 AS TO_DATE
  FROM DUAL;

SELECT DISTINCT OUTBOUND_DATE
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 1 
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + 10
 ORDER BY OUTBOUND_DATE;
 
--29)
SELECT *
  FROM CS_NO
 WHERE NO <= 10;
 
--30)
SELECT LEVEL AS NO
  FROM DUAL
 CONNECT BY LEVEL <= 10;

--31) 실전문제 1번으로 다양한 방식으로 하는 중
SELECT NO
  FROM CS_NO
 WHERE NO <= :DAYS;
 
SELECT LEVEL AS NO
  FROM DUAL
 CONNECT BY LEVEL <= :DAYS;
 
SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + NO AS ORG_DATE
  FROM CS_NO
 WHERE NO <= :DAYS;

--31 인라인뷰)
SELECT *
  FROM (
        SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + NO AS ORG_DATE
          FROM CS_NO
         WHERE NO <= :DAYS
        ) M1
 WHERE EXISTS (
               SELECT *
                 FROM LO_OUT_M S1
                WHERE S1.OUTBOUND_DATE = M1.ORG_DATE
               );
 
--31 **) 
SELECT *
  FROM CS_NO
 WHERE NO <= TO_DATE(:TO_DATE, 'YYYY-MM-DD') - TO_DATE(:FROM_DATE, 'YYYY-MM-DD')+ 1;
 
SELECT TO_DATE(:TO_DATE, 'YYYY-MM-DD') - TO_DATE(:FROM_DATE, 'YYYY-MM-DD')
  FROM DUAL;
  
SELECT TO_DATE(:FROM_DATE, 'YYYY-MM-DD') + NO - 1
  FROM CS_NO
WHERE NO <= TO_DATE(:TO_DATE, 'YYYY-MM-DD') - TO_DATE(:FROM_DATE, 'YYYY-MM-DD')+ 1;

--32)
SELECT BRAND_CD, ITEM_CD,SUM(ORDER_QTY)
  FROM A_OUT_D
 GROUP BY BRAND_CD, ITEM_CD
 ORDER BY BRAND_CD, ITEM_CD;
 
--33)
SELECT BRAND_CD, ITEM_CD, SUM_QTY
       ,TRUNC(SUM_QTY / :QTY_IN_BOX) AS BOX_CNT
       ,MOD  (SUM_QTY , :QTY_IN_BOX) AS PCS_CNT 
  FROM ( --1단계. 브랜드/상품별 주문수량 합계 구하기
        SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY BRAND_CD, ITEM_CD
         ORDER BY BRAND_CD, ITEM_CD
        )
;

--34)
SELECT ROWNUM AS RNK
       , ITEM_CD
       , QTY_IN_BOX
       , ORDER_QTY
       ,TRUNC(ORDER_QTY / QTY_IN_BOX) AS BOX_CNT
       ,MOD  (ORDER_QTY , QTY_IN_BOX) AS PCS_CNT
       ,CEIL (ORDER_QTY / QTY_IN_BOX) AS BOX_CNT_TOT
  FROM (--1) 상품코드/박수입수별 출고 수량의 합계 구하기
          SELECT ITEM_CD
                 ,MAX(QTY_IN_BOX) AS QTY_IN_BOX
                 ,SUM(ORDER_QTY) AS ORDER_QTY
            FROM LO_OUT_D
           WHERE INVOICE_NO BETWEEN '346724706262' AND '346724706762'
           GROUP BY ITEM_CD
           ORDER BY ORDER_QTY DESC
        )
  WHERE ROWNUM <= 5;
  
--34-(1))
SELECT ITEM_CD
               ,MAX(QTY_IN_BOX) AS QTY_IN_BOX
               ,SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_D
         WHERE INVOICE_NO BETWEEN '346724706262' AND '346724706762'
         GROUP BY ITEM_CD
